/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE mode1BaseService PLEASE EDIT ../mode1.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Mode1 } from '../../domain/ngcpos_db/mode1';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Mode1.service.ts
 */

/*
 * SCHEMA DB Mode1
 *
	{
		Test1: {
			type: 'String',
			required : true
		},
		Test2: {
			type: 'Number',
			enum : ["01", "02", "03", "04"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class Mode1BaseService {

    contextUrl: string = environment.endpoint + '/mode1';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * Mode1Service.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * Mode1Service.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Mode1[]> {
        return this.http
            .get<Mode1[]>(this.contextUrl)
            .pipe(map(data => data));
    }


    // Custom APIs

}
